version: '3'

services:
  app:
    build:
      context: .
    container_name: hospital-appointment
    ports:
      - "8080:8080"
    networks:
      - spring-postgres
    depends_on:
      - postgres
    env_file: ./.env
  postgres:
    image: 'postgres:15.1-alpine'
    ports:
      - "5433:5432"
    networks:
      - spring-postgres
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${DATASOURCE_PASSWORD}
volumes:
  db-data:
networks:
  spring-postgres: