version: '3'

services:
  app:
    build:
      context: .
    container_name: hospital-appointment
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file: ./.env
  postgres:
    image: 'postgres:15.1-alpine'
    ports:
      - "5433:5432"
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d
    env_file: ./.env
