spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=hospital
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jackson:
    default-property-inclusion: NON_NULL
  liquibase:
    change-log: classpath:db/liquibaseConfig.xml
    liquibase-schema: hospital
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration

security:
  jwt:
    expiration-time-access: 5
    expiration-time-refresh: 336
    secret: "sdfkhpofgsfg;ly@TYnldw.x[dpuyq,snBJ?fwfergkegDV3RFdsXDdSfsWs"


hospital:
  hours:
    start: "08:00"
    finish: "20:00"
    minutes-range: 60
mybatis:
  mapper-locations: classpath:mapper/*.xml


